version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: examplepassword

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: disc-golf-api
    ports:
      - "5555:5555"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://root:examplepassword@mongodb:27017/disc_golf  # Update with your MongoDB connection URI
